$schema: https://json-schema.org/draft/2020-12/schema
$id: https://raw.githubusercontent.com/wmo-im/bufr2geojson/main/bufr2geojson/resources/schemas/wmo-om-profile-geojson.yaml
title: WMO GeoJSON profile for observations and measurements
description: WMO GeoJSON profile for observations and measurements

allOf:
  - $ref: https://raw.githubusercontent.com/opengeospatial/ogcapi-features/master/core/openapi/schemas/featureGeoJSON.yaml
properties:
  allOf:
    - $ref: https://raw.githubusercontent.com/opengeospatial/ogcapi-common/master/core/openapi/schemas/confClasses.yaml
  conformsTo:
    $ref: "https://raw.githubusercontent.com/opengeospatial/ogcapi-common/master/core/openapi/schemas/confClasses.yaml#/properties/conformsTo"
    items:
      enum:
        - http://www.wmo.int/spec/om-profile-1/1.0/req/geojson
  properties:
    type: object
    properties:
      phenomenonTime:
        type: string
        format: date
        description: TODO
      resultTime:
        type: string
        format: date
        description: TODO
      name:
        type: string
        description: TODO
      description:
        type: string
        description: TODO
      units:
        type: string
        description: TODO
      value:
        type: number
        description: TODO
      metadata:
        type: object
        description: TODO
    required:
      - phenomemonTime
      - name
      - value