name: tests ⚙️

on: [ push, pull_request ]

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      name: Setup Python ${{ matrix.python-version }}
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
        conda-channels: anaconda, conda-forge

    - name: Install udunits
      run: sudo apt-get install -y libudunits2-0

    - name: Install requirements 📦
      run: |
        conda install eccodes
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install -e "git+https://github.com/tomkralidis/jsonschema@ref-yaml#egg=jsonschema"
        pip3 install -r requirements-dev.txt
        python3 setup.py install
    - name: run tests ⚙️
      run: |
        export ECCODES_DEFINITION_PATH=/opt/conda/share/eccodes/definitions 
        cd tests
        pytest
    - name: run flake8 ⚙️
      run: |
        flake8 --exclude src/jsonschema

